spring:
  liquibase:
    changeLog: "classpath: migrations/master.yaml"
    #enabled: false

  datasource:
    url:  jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver