app:
  test: 4
  scheduler:
    interval: 1500000
    database-access-type: jdbc

springdoc:
  swagger-ui:
    path: swagger-ui
server:
  port: 8080

github:
  base-url: https://api.github.com

stackoverflow:
  base-url: https://api.stackexchange.com/2.3

bot:
  base-url: "http://localhost:8081"
spring:
  liquibase:
    changeLog: "classpath: /migrations/master.yaml"
    enabled: false

  datasource:
    url:  jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  main:
    allow-circular-references: true