app:
  test: 4
  scheduler:
    interval: 1500000
  database-access-type: jdbc
  checkPeriodHours: 0
  exchangeName: scrapperExchange
  queueName: scrapperQueue
  useQueue: false


springdoc:
  swagger-ui:
    path: swagger-ui
server:
  port: 8080

github:
  base-url: https://api.github.com

stackoverflow:
  base-url: https://api.stackexchange.com/2.3

bot:
  base-url: "http://localhost:8081"

spring:
  liquibase:
    changeLog: "classpath: /migrations/master.yaml"
    enabled: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  application:
    name: scrapper
  main:
    allow-circular-references: true

management:
  server:
    port: 8082
  endpoint:
    health:
      show-details: always
    info:
    prometheus:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
      path-mapping:
        prometheus: metrics
    enabled-by-default: true
  metrics:
    tags:
      application: '${spring.application.name}'
