app:
  test: 5
  exchangeName: scrapper
  queueName: scrapper
#    routing-key: scrapper

springdoc:
  swagger-ui:
    path: /swagger-ui
server:
  port: 8081

ApplicationConfig:
  token: ${TOKEN}

scrapper:
  url: http://localhost:8080

spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver