name: Java CI for bot with Maven
on:
  push:
    paths:
      - 'bot/**'
    branches: ["main"]
  pull_request:
    paths:
      - 'bot/**'
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn package -pl bot -am
      - name: Build Dockerfile
        run: docker build -f bot/Dockerfile -t bot

