name: Java CI for scrapper with Maven
on:
  push:
    paths:
      - 'scrapper/**'
    branches: ["main"]
  pull_request:
    paths:
      - 'scrapper/**'
    branches: ["*"]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "scrapper"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn package -pl scrapper -am

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.TOKEN_GITHUB }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build Docker image
        run: docker build -f bot/Dockerfile --force-rm -t ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest .

      - name: Push Docker image to GitHub Container Registry
        run: docker push ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest
